version: '3'

services:
  be-vaultafrica:
    image: vaultafrica/moneyvault
    container_name: moneyvault-be
    restart: unless-stopped
    ports:
      - "3001:${PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      CONNECTION_TIMEOUT: ${CONNECTION_TIMEOUT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_HOST: ${EMAIL_HOST}
      EXPIRES_IN: ${EXPIRES_IN}
      JWT_KEY: ${JWT_KEY}
      OTP_EXPIRATION: ${OTP_EXPIRATION}
    depends_on:
      - db

  db:
    image: postgres
    container_name: moneyvault-db
    restart: always
    ports:
      - "5555:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

