version: '3'

services:
  be-vaultafrica:
    image: vaultafrica/moneyvault
    container_name: moneyvault-be
    restart: unless-stopped
    ports:
      - "3001:${PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      CONNECTION_TIMEOUT: ${CONNECTION_TIMEOUT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_HOST: ${EMAIL_HOST}
      EXPIRES_IN: ${EXPIRES_IN}
      JWT_KEY: ${JWT_KEY}
      OTP_EXPIRATION: ${OTP_EXPIRATION}
      SECRET: ${SECRET}
      API_KEY: ${API_KEY}
      FIXED_SAVINGS_INTEREST_RATE: ${FIXED_SAVINGS_INTEREST_RATE}
      FIXED_DEPOSIT_INTEREST_RATE: ${FIXED_DEPOSIT_INTEREST_RATE}
      DOLLAR_TO_NAIRA_RATE: ${DOLLAR_TO_NAIRA_RATE}
      NAIRA_TO_DOLLAR_RATE: ${NAIRA_TO_DOLLAR_RATE}
      DOLLAR_CONVERSION_CHARGE: ${DOLLAR_CONVERSION_CHARGE}
      LOAN_LIMIT: ${LOAN_LIMIT}
      SERVICE_FEE: ${SERVICE_FEE}
      JOINT_SAVINGS_INTEREST: ${JOINT_SAVINGS_INTEREST}
      INVITATION_EMAIL: ${INVITATION_EMAIL}
      URL: ${URL}
      TRANSACTION_REF: ${TRANSACTION_REF}
      AUTH_PROVIDER: ${AUTH_PROVIDER}
    depends_on:
      - db

  db:
    image: postgres
    container_name: moneyvault-db
    restart: always
    ports:
      - "5555:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

