version: '3'

services:
  be-vaultafrica:
    image: vaultafrica/moneyvault
    container_name: moneyvault-be
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS]
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db

  db:
    image: postgres
    container_name: moneyvault-be
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}

